
//! Unicode 14.0 view of general category and character names.
//!
//! The Python original runs on `unicodedata` pinned to Unicode 14.0 (CPython
//! 3.11); the Rust crates track a newer Unicode. Code points assigned after 14.0
//! are reported as unassigned (`Cn`, name `UNKNOWN`) to keep decisions and
//! labels identical. Table generated by `tests/gen_unidata14.py`.

use unicode_general_category::{get_general_category, GeneralCategory as Gc};

fn v14_unassigned(cp: u32) -> bool {
    V14_UNASSIGNED
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                core::cmp::Ordering::Greater
            } else if cp > hi {
                core::cmp::Ordering::Less
            } else {
                core::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

pub fn category(cp: u32) -> Gc {
    if v14_unassigned(cp) {
        return Gc::Unassigned;
    }
    // Only category change between Unicode 14.0 and the crate's version.
    if cp == 0x1171E {
        return Gc::NonspacingMark;
    }
    match char::from_u32(cp) {
        Some(c) => get_general_category(c),
        None => Gc::Surrogate,
    }
}

pub fn name(ch: char) -> String {
    if v14_unassigned(ch as u32) {
        return "UNKNOWN".to_string();
    }
    match unicode_names2::name(ch) {
        Some(n) => n.to_string(),
        None => "UNKNOWN".to_string(),
    }
}

pub fn category_abbr(g: Gc) -> &'static str {
    use Gc::*;
    match g {
        UppercaseLetter => "Lu",
        LowercaseLetter => "Ll",
        TitlecaseLetter => "Lt",
        ModifierLetter => "Lm",
        OtherLetter => "Lo",
        NonspacingMark => "Mn",
        SpacingMark => "Mc",
        EnclosingMark => "Me",
        DecimalNumber => "Nd",
        LetterNumber => "Nl",
        OtherNumber => "No",
        ConnectorPunctuation => "Pc",
        DashPunctuation => "Pd",
        OpenPunctuation => "Ps",
        ClosePunctuation => "Pe",
        InitialPunctuation => "Pi",
        FinalPunctuation => "Pf",
        OtherPunctuation => "Po",
        MathSymbol => "Sm",
        CurrencySymbol => "Sc",
        ModifierSymbol => "Sk",
        OtherSymbol => "So",
        SpaceSeparator => "Zs",
        LineSeparator => "Zl",
        ParagraphSeparator => "Zp",
        Control => "Cc",
        Format => "Cf",
        Surrogate => "Cs",
        PrivateUse => "Co",
        _ => "Cn",
    }
}

const V14_UNASSIGNED: &[(u32, u32)] = &[
    (0x88F, 0x88F),
    (0x897, 0x897),
    (0xC5C, 0xC5C),
    (0xCDC, 0xCDC),
    (0xCF3, 0xCF3),
    (0xECE, 0xECE),
    (0x1ACF, 0x1ADD),
    (0x1AE0, 0x1AEB),
    (0x1B4E, 0x1B4F),
    (0x1B7F, 0x1B7F),
    (0x1C89, 0x1C8A),
    (0x20C1, 0x20C1),
    (0x2427, 0x2429),
    (0x2B96, 0x2B96),
    (0x2FFC, 0x2FFF),
    (0x31E4, 0x31E5),
    (0x31EF, 0x31EF),
    (0xA7CB, 0xA7CF),
    (0xA7D2, 0xA7D2),
    (0xA7D4, 0xA7D4),
    (0xA7DA, 0xA7DC),
    (0xA7F1, 0xA7F1),
    (0xFBC3, 0xFBD2),
    (0xFD90, 0xFD91),
    (0xFDC8, 0xFDCE),
    (0x105C0, 0x105F3),
    (0x10940, 0x10959),
    (0x10D40, 0x10D65),
    (0x10D69, 0x10D85),
    (0x10D8E, 0x10D8F),
    (0x10EC2, 0x10EC7),
    (0x10ED0, 0x10ED8),
    (0x10EFA, 0x10EFF),
    (0x1123F, 0x11241),
    (0x11380, 0x11389),
    (0x1138B, 0x1138B),
    (0x1138E, 0x1138E),
    (0x11390, 0x113B5),
    (0x113B7, 0x113C0),
    (0x113C2, 0x113C2),
    (0x113C5, 0x113C5),
    (0x113C7, 0x113CA),
    (0x113CC, 0x113D5),
    (0x113D7, 0x113D8),
    (0x113E1, 0x113E2),
    (0x116D0, 0x116E3),
    (0x11B00, 0x11B09),
    (0x11B60, 0x11B67),
    (0x11BC0, 0x11BE1),
    (0x11BF0, 0x11BF9),
    (0x11DB0, 0x11DDB),
    (0x11DE0, 0x11DE9),
    (0x11F00, 0x11F10),
    (0x11F12, 0x11F3A),
    (0x11F3E, 0x11F5A),
    (0x1342F, 0x1342F),
    (0x13439, 0x13455),
    (0x13460, 0x143FA),
    (0x16100, 0x16139),
    (0x16D40, 0x16D79),
    (0x16EA0, 0x16EB8),
    (0x16EBB, 0x16ED3),
    (0x16FF2, 0x16FF6),
    (0x18CFF, 0x18CFF),
    (0x18D80, 0x18DF2),
    (0x1B132, 0x1B132),
    (0x1B155, 0x1B155),
    (0x1CC00, 0x1CCFC),
    (0x1CD00, 0x1CEB3),
    (0x1CEBA, 0x1CED0),
    (0x1CEE0, 0x1CEF0),
    (0x1D2C0, 0x1D2D3),
    (0x1DF25, 0x1DF2A),
    (0x1E030, 0x1E06D),
    (0x1E08F, 0x1E08F),
    (0x1E4D0, 0x1E4F9),
    (0x1E5D0, 0x1E5FA),
    (0x1E5FF, 0x1E5FF),
    (0x1E6C0, 0x1E6DE),
    (0x1E6E0, 0x1E6F5),
    (0x1E6FE, 0x1E6FF),
    (0x1F6D8, 0x1F6D8),
    (0x1F6DC, 0x1F6DC),
    (0x1F774, 0x1F77F),
    (0x1F7D9, 0x1F7D9),
    (0x1F8B2, 0x1F8BB),
    (0x1F8C0, 0x1F8C1),
    (0x1F8D0, 0x1F8D8),
    (0x1FA54, 0x1FA57),
    (0x1FA75, 0x1FA77),
    (0x1FA87, 0x1FA8A),
    (0x1FA8E, 0x1FA8F),
    (0x1FAAD, 0x1FAAF),
    (0x1FABB, 0x1FABF),
    (0x1FAC6, 0x1FAC6),
    (0x1FAC8, 0x1FAC8),
    (0x1FACD, 0x1FACF),
    (0x1FADA, 0x1FADC),
    (0x1FADF, 0x1FADF),
    (0x1FAE8, 0x1FAEA),
    (0x1FAEF, 0x1FAEF),
    (0x1FAF7, 0x1FAF8),
    (0x1FBCB, 0x1FBEF),
    (0x1FBFA, 0x1FBFA),
    (0x2B739, 0x2B73F),
    (0x2CEA2, 0x2CEAD),
    (0x2EBF0, 0x2EE5D),
    (0x31350, 0x33479),
];
