#!/usr/bin/env python3
"""Generate the Rust parity fixtures for wm-image.

Imports ``service/scripts/image_meta.py`` (the reference implementation),
builds synthetic images (written to ``tests/data/``) plus copies of the repo
fixture images, runs every inspector / stripper / ``inspect_image`` /
``clean_image`` on them (and on truncated / byte-mutated variants), and records
the results -- with sha256 of every strip output -- in
``tests/data/parity.json``. ``tests/parity.rs`` replays the same inputs through
the Rust crate and demands identical results.

Run from anywhere::

    python3 wasm/crates/wm-image/tests/gen_parity.py

The Python run stubs out the pieces that are deliberately not ported:
``run_optional_tools`` (c2patool/exiftool), SynthID scoring and ``which``
(so no exiftool pass rewrites the output).
"""

from __future__ import annotations

import hashlib
import json
import random
import shutil
import struct
import sys
import tempfile
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPO = HERE.parents[3]
SCRIPTS = REPO / "service" / "scripts"
TESTS = REPO / "tests"
sys.path.insert(0, str(SCRIPTS))
sys.path.insert(0, str(TESTS))

import image_meta as im  # noqa: E402

# --- stub the non-ported pieces --------------------------------------------
im.run_optional_tools = lambda path, include_exiftool=True: {}
im.run_synthid_score = lambda *a, **k: None
im.which = lambda cmd: None

import test_avif_heic as T_AVIF  # noqa: E402
import test_clean_image as T_CLEAN  # noqa: E402
import test_image_formats_bmp_gif_tiff as T_BGT  # noqa: E402

XMP_UUID = im.XMP_UUID
C2PA_UUID = im.C2PA_BMFF_UUID


def sha(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


# ---------------------------------------------------------------------------
# synthetic builders
# ---------------------------------------------------------------------------


def png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


PNG_SIG = b"\x89PNG\r\n\x1a\n"
IHDR = png_chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0))
IDAT = png_chunk(b"IDAT", zlib.compress(b"\x00\x00\x00"))
IEND = png_chunk(b"IEND", b"")


def png_with(*chunks: bytes, end: bool = True, idat: bytes = IDAT) -> bytes:
    return PNG_SIG + IHDR + b"".join(chunks) + idat + (IEND if end else b"")


def text(key: str, value: str) -> bytes:
    return key.encode("latin-1") + b"\x00" + value.encode("latin-1")


def itxt(key: bytes, comp: int, lang: bytes, tkey: bytes, value: bytes) -> bytes:
    return key + b"\x00" + bytes([comp, 0]) + lang + b"\x00" + tkey + b"\x00" + value


def make_png_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    c["png_clean.png"] = png_with()
    c["png_text_c2pa.png"] = T_CLEAN._minimal_png_with_text()
    c["png_software_chatgpt.png"] = png_with(png_chunk(b"tEXt", text("Software", "ChatGPT")))
    c["png_software_lower.png"] = png_with(png_chunk(b"tEXt", text("software", "chatgpt 4")))
    c["png_creator_dalle.png"] = png_with(png_chunk(b"tEXt", text("Creator", "DALL-E 3")))
    c["png_params_sdxl.png"] = png_with(
        png_chunk(b"tEXt", text("parameters", "Steps: 20, Sampler: DPM++ 2M, Model: SDXL base 1.0"))
    )
    c["png_params_plain_model.png"] = png_with(
        png_chunk(b"tEXt", text("parameters", "Steps: 20, Model: sd_xl_base_1.0"))
    )
    c["png_multi_products.png"] = png_with(
        png_chunk(b"tEXt", text("Software", "Adobe Firefly via Gemini Imagen Grok"))
    )
    c["png_comment_gemini.png"] = png_with(
        png_chunk(b"tEXt", text("Comment", "Hiking near the Gemini constellation with my dog Sora"))
    )
    c["png_comment_generated_by.png"] = png_with(png_chunk(b"tEXt", text("Comment", "Generated by AI")))
    c["png_comment_benign.png"] = png_with(png_chunk(b"tEXt", text("Comment", "a nice photo of a cat")))
    c["png_key_whitespace.png"] = png_with(
        png_chunk(b"tEXt", b"  Software \x85\xa0\x00ChatGPT")
    )
    c["png_key_1c.png"] = png_with(png_chunk(b"tEXt", b"\x1cSoftware\x1f\x00Midjourney"))
    c["png_text_nonul.png"] = png_with(png_chunk(b"tEXt", b"SoftwareChatGPT"))
    c["png_ztxt_software.png"] = png_with(
        png_chunk(b"zTXt", b"Software\x00\x00" + zlib.compress(b"ChatGPT"))
    )
    c["png_ztxt_comment_gen.png"] = png_with(
        png_chunk(b"zTXt", b"Comment\x00\x00" + zlib.compress(b"Generated by AI"))
    )
    c["png_ztxt_short.png"] = png_with(png_chunk(b"zTXt", b"Software\x00\x00"))
    c["png_ztxt_corrupt.png"] = png_with(png_chunk(b"zTXt", b"Software\x00\x00" + b"\x78\x9c\xff\xff\xff"))
    z = zlib.compress(b"x" * 100 + b"ChatGPT " + b"c2pa" * 20, 9)
    c["png_ztxt_truncated_stream.png"] = png_with(png_chunk(b"zTXt", b"Software\x00\x00" + z[:-9]))
    c["png_ztxt_bad_adler.png"] = png_with(
        png_chunk(b"zTXt", b"Software\x00\x00" + z[:-1] + bytes([z[-1] ^ 1]))
    )
    c["png_ztxt_bomb.png"] = png_with(
        png_chunk(b"zTXt", b"Software\x00\x00" + zlib.compress(b"\x00" * (3 << 20), 9))
    )
    c["png_ztxt_bomb_marker.png"] = png_with(
        png_chunk(b"zTXt", b"Comment\x00\x00" + zlib.compress(b"c2pa" + b"\x00" * (3 << 20), 9))
    )
    c["png_ztxt_1mib_exact.png"] = png_with(
        png_chunk(b"zTXt", b"Comment\x00\x00" + zlib.compress(b"\x00" * (1 << 20), 9))
    )
    c["png_ztxt_1mib_minus1.png"] = png_with(
        png_chunk(b"zTXt", b"Comment\x00\x00" + zlib.compress(b"\x00" * ((1 << 20) - 1), 9))
    )
    c["png_itxt_software.png"] = png_with(png_chunk(b"iTXt", b"Software\x00\x00\x00\x00\x00ChatGPT"))
    c["png_itxt_comp_comment.png"] = png_with(
        png_chunk(b"iTXt", b"Comment\x00\x01\x00\x00\x00" + zlib.compress(b"Generated by AI"))
    )
    c["png_itxt_invalid_utf8.png"] = png_with(
        png_chunk(b"iTXt", itxt(b"Software", 0, b"en", b"Software", b"\xff\xfe ChatGPT \xc3\xed\xa0\x80 tail\xc3"))
    )
    c["png_itxt_unicode.png"] = png_with(
        png_chunk(b"iTXt", itxt(b"Creator", 0, b"en", "créateur".encode(), "KLING Kling Ωmega".encode()))
    )
    c["png_itxt_bad_zlib.png"] = png_with(
        png_chunk(b"iTXt", b"Software\x00\x01\x00\x00\x00" + b"notzlib")
    )
    c["png_itxt_short.png"] = png_with(png_chunk(b"iTXt", b"Software\x00\x00\x00"))
    c["png_cabx.png"] = png_with(png_chunk(b"caBX", b"jumb manifest bytes"))
    c["png_c2_chunk.png"] = png_with(png_chunk(b"c2pa", b"anything"))
    c["png_jumb_chunk.png"] = png_with(png_chunk(b"jumb", b"anything"))
    c["png_exif_openai.png"] = png_with(png_chunk(b"eXIf", b"Exif\x00\x00OpenAI camera"))
    c["png_exif_clean.png"] = png_with(png_chunk(b"eXIf", b"Exif\x00\x00Canon"))
    c["png_private_marker.png"] = png_with(png_chunk(b"prVt", b"has contentauth inside"))
    c["png_private_benign.png"] = png_with(png_chunk(b"prVt", b"nothing here"))
    c["png_iccp_marker.png"] = png_with(png_chunk(b"iCCP", b"c2pa profile\x00\x00data"))
    c["png_name_marker.png"] = png_with(png_chunk(b"jumB", b"x"))
    c["png_idat_marker.png"] = png_with(idat=png_chunk(b"IDAT", b"pixels c2pa pixels"))
    c["png_trailing_after_iend.png"] = png_with() + b"trailing junk c2pa"
    c["png_no_iend.png"] = png_with(png_chunk(b"tEXt", text("Comment", "c2pa")), end=False)
    c["png_short_tail.png"] = png_with() + b"abc"
    c["png_truncated_chunk.png"] = png_with(png_chunk(b"tEXt", text("Software", "ChatGPT")))[:-30]
    c["png_huge_length.png"] = PNG_SIG + IHDR + struct.pack(">I", 0xFFFFFFF0) + b"tEXtSoftware"
    c["png_combo.png"] = png_with(
        png_chunk(b"tEXt", text("Software", "ChatGPT")),
        png_chunk(b"zTXt", b"Author\x00\x00" + zlib.compress(b"someone")),
        png_chunk(b"iTXt", b"XML:com.adobe.xmp\x00\x00\x00\x00\x00<x digitalSourceType='trainedAlgorithmicMedia'/>"),
        png_chunk(b"eXIf", b"Exif\x00\x00"),
        png_chunk(b"caBX", b"c2pa"),
        png_chunk(b"pHYs", struct.pack(">IIB", 2835, 2835, 1)),
    )
    c["png_sig_only.png"] = PNG_SIG
    c["png_sig_plus.png"] = PNG_SIG + b"\x00\x00\x00"
    return c


JPEG_1X1 = T_CLEAN.JPEG_1X1


def jseg(marker: int, payload: bytes) -> bytes:
    return bytes([0xFF, marker]) + struct.pack(">H", len(payload) + 2) + payload


def jpeg_with(*segs: bytes) -> bytes:
    return JPEG_1X1[:2] + b"".join(segs) + JPEG_1X1[2:]


def make_jpeg_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    c["jpeg_1x1.jpg"] = JPEG_1X1
    c["jpeg_app11_minimal.jpg"] = T_CLEAN._minimal_jpeg_with_app11()
    for i, comment in enumerate(
        [
            b"Family vacation, Shanghai, 2026-08-21",
            b"Generated by ImageMagick 7.1",
            b"Claude Monet retrospective",
            b"JUMBO family photo",
            b"Jumble sale poster",
            b"Generated by AI with OpenAI",
            b"contentcredentials c2pa manifest note",
            b"made with SynthID",
            b"dcterms:provenance here",
            b"AI generated image",
            b"CAI: something",
            b"digitalSourceType=trainedAlgorithmicMedia",
            b"",
        ]
    ):
        c[f"jpeg_com_{i}.jpg"] = jpeg_with(jseg(0xFE, comment))
    c["jpeg_app1_xmp_openai.jpg"] = jpeg_with(
        jseg(0xE1, b"http://ns.adobe.com/xap/1.0/\x00<x:xmpmeta>OpenAI generated</x:xmpmeta>")
    )
    c["jpeg_app1_exif_clean.jpg"] = jpeg_with(jseg(0xE1, b"Exif\x00\x00II*\x00Canon"))
    c["jpeg_app1_exif_anthropic.jpg"] = jpeg_with(jseg(0xE1, b"Exif\x00\x00Anthropic Claude"))
    c["jpeg_app2_icc.jpg"] = jpeg_with(jseg(0xE2, b"ICC_PROFILE\x00\x01\x01Claude profile"))
    c["jpeg_app2_icc_clean.jpg"] = jpeg_with(jseg(0xE2, b"ICC_PROFILE\x00\x01\x01plain profile"))
    c["jpeg_app13_dst.jpg"] = jpeg_with(jseg(0xED, b"Photoshop 3.0\x008BIM digitalSourceType"))
    c["jpeg_app14_marker.jpg"] = jpeg_with(jseg(0xEE, b"Adobe\x00AIGC"))
    c["jpeg_app3_marker.jpg"] = jpeg_with(jseg(0xE3, b"has c2pa marker but APP3"))
    c["jpeg_app0_marker.jpg"] = jpeg_with(jseg(0xE0, b"JFIF\x00 c2pa"))
    c["jpeg_app11_jumb.jpg"] = jpeg_with(
        jseg(0xEB, b"JP\x00\x00\x00\x01\x00\x00jumb c2pa.manifest contentcredentials")
    )
    c["jpeg_app11_plain.jpg"] = jpeg_with(jseg(0xEB, b"nothing"))
    c["jpeg_app4_plain.jpg"] = jpeg_with(jseg(0xE4, b"plain"))
    c["jpeg_multi.jpg"] = jpeg_with(
        jseg(0xE1, b"Exif\x00\x00Canon"),
        jseg(0xFE, b"hello"),
        jseg(0xEB, b"c2pa"),
        jseg(0xE2, b"ICC_PROFILE"),
        jseg(0xED, b"8BIM"),
    )
    c["jpeg_bad_seglen.jpg"] = JPEG_1X1[:2] + b"\xff\xe1\x00\x01" + JPEG_1X1[2:]
    c["jpeg_seglen_overrun.jpg"] = JPEG_1X1[:2] + b"\xff\xe1\xff\xf0abc" + JPEG_1X1[2:]
    c["jpeg_fill_bytes.jpg"] = JPEG_1X1[:2] + b"\xff\xff\xff" + jseg(0xE1, b"Exif\x00\x00x")[1:] + JPEG_1X1[2:]
    c["jpeg_rst_markers.jpg"] = JPEG_1X1[:2] + b"\xff\xd0\xff\xd7\xff\xd8" + jseg(0xFE, b"x") + JPEG_1X1[2:]
    c["jpeg_entropy_c2pa.jpg"] = JPEG_1X1[:-2] + b"c2pa" + JPEG_1X1[-2:]
    c["jpeg_entropy_jumb_only.jpg"] = JPEG_1X1[:-2] + b"jumb" + JPEG_1X1[-2:]
    c["jpeg_no_sos.jpg"] = JPEG_1X1[:2] + jseg(0xFE, b"c2pa") + b"\xff\xd9"
    c["jpeg_trailing.jpg"] = JPEG_1X1 + b"trailing OpenAI"
    c["jpeg_garbage_between.jpg"] = JPEG_1X1[:2] + jseg(0xFE, b"hi") + b"garbage" + JPEG_1X1[2:]
    c["jpeg_soi_only.jpg"] = b"\xff\xd8"
    c["jpeg_soi_ff.jpg"] = b"\xff\xd8\xff"
    c["jpeg_soi_app.jpg"] = b"\xff\xd8\xff\xe1\x00"
    c["jpeg_truncated_sos.jpg"] = JPEG_1X1[:2] + jseg(0xFE, b"x") + b"\xff\xda\x00"
    c["jpeg_double_soi.jpg"] = b"\xff\xd8\xff\xd8" + JPEG_1X1[2:]
    return c


def webp_chunk(fourcc: bytes, payload: bytes, pad: bytes | None = None) -> bytes:
    padding = (pad if pad is not None else b"\x00") if len(payload) & 1 else b""
    return fourcc + struct.pack("<I", len(payload)) + payload + padding


def webp(*chunks: tuple, riff_delta: int = 0, tail: bytes = b"") -> bytes:
    body = b"WEBP" + b"".join(webp_chunk(*c) for c in chunks) + tail
    return b"RIFF" + struct.pack("<I", len(body) + riff_delta) + body


def make_webp_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    c["webp_c2pa_xmp.webp"] = T_CLEAN._minimal_webp(
        (b"VP8X", b"\x04" + b"\x00" * 9),
        (b"VP8 ", b"image-data"),
        (b"XMP ", b"generator=OpenAI"),
        (b"C2PA", b"jumb c2pa manifest"),
    )
    c["webp_payload_text.webp"] = T_CLEAN._minimal_webp((b"VP8 ", b"ordinary pixels mentioning c2pa"))
    c["webp_truncated.webp"] = b"RIFF\x10\x00\x00\x00WEBPC2PA\x10\x00\x00\x00short"
    base = T_CLEAN._minimal_webp((b"VP8 ", b"image-data"))
    c["webp_size_mismatch.webp"] = base[:4] + struct.pack("<I", len(base)) + base[8:]
    c["webp_exif_generated_by.webp"] = webp(
        (b"VP8X", b"\x08" + b"\x00" * 9), (b"VP8 ", b"abcd"), (b"EXIF", b"Exif\x00\x00Generated by X")
    )
    c["webp_all_meta_clean.webp"] = webp(
        (b"VP8X", b"\x2c" + b"\x00" * 9),
        (b"ICCP", b"icc profile"),
        (b"VP8 ", b"abcd"),
        (b"EXIF", b"Exif\x00\x00Canon"),
        (b"XMP ", b"<x:xmpmeta/>"),
    )
    c["webp_iccp_marker.webp"] = webp(
        (b"VP8X", b"\x2c" + b"\x00" * 9), (b"ICCP", b"c2pa icc"), (b"VP8 ", b"abcd"),
        (b"EXIF", b"Exif"), (b"XMP ", b"openai"),
    )
    c["webp_odd_chunk_pad.webp"] = webp((b"VP8 ", b"abc", b"\x7f"), (b"EXIF", b"odd", b"\x01"))
    c["webp_lower_c2pa.webp"] = webp((b"VP8 ", b"abcd"), (b"c2pa", b"manifest"))
    c["webp_trailing.webp"] = webp((b"VP8 ", b"abcd"), tail=b"xyz")
    c["webp_trailing_riff_ok.webp"] = webp((b"VP8 ", b"abcd"), tail=b"xyz", riff_delta=0)
    c["webp_empty.webp"] = b"RIFF\x04\x00\x00\x00WEBP"
    c["webp_vp8x_empty_payload.webp"] = webp((b"VP8X", b""), (b"XMP ", b"c2pa"))
    c["webp_xmp_clean.webp"] = webp((b"VP8 ", b"abcd"), (b"XMP ", b"<x:xmpmeta/>"))
    c["webp_huge_len.webp"] = b"RIFF\x18\x00\x00\x00WEBPXMP \xff\xff\xff\xff" + b"abcd"
    c["webp_short_hdr.webp"] = b"RIFF\x04\x00\x00\x00WEB"
    return c


def box(fourcc: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + fourcc + payload


def box64(fourcc: bytes, payload: bytes) -> bytes:
    return struct.pack(">I4sQ", 1, fourcc, len(payload) + 16) + payload


def fullbox(fourcc: bytes, payload: bytes, version: int = 0, flags: int = 0) -> bytes:
    return box(fourcc, struct.pack(">I", (version << 24) | flags) + payload)


def make_isobmff_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    c["avif_c2pa_xmp.avif"] = T_AVIF._minimal_avif_with_c2pa_and_xmp()
    c["heic_xmp.heic"] = T_AVIF._minimal_heic_with_xmp()
    ftyp_avif = box(b"ftyp", b"avif\x00\x00\x00\x00avifmif1")
    ftyp_heic = box(b"ftyp", b"heic\x00\x00\x00\x00mif1heic")
    mdat = box(b"mdat", b"\x00\x01\x02\x03image")
    hdlr = fullbox(b"hdlr", b"\x00\x00\x00\x00pict" + b"\x00" * 12 + b"PictureHandler\x00")
    c["avif_clean.avif"] = ftyp_avif + fullbox(b"meta", hdlr) + mdat
    c["avif_toplevel_c2pa_uuid.avif"] = ftyp_avif + fullbox(b"meta", hdlr) + box(b"uuid", C2PA_UUID + b"\x00manifest bytes without marker") + mdat
    c["avif_toplevel_c2pa_uuid_prefix.avif"] = ftyp_avif + box(b"uuid", b"\x00\x00\x00\x00" + C2PA_UUID + b"merkle") + mdat
    c["avif_meta_c2pa_uuid.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", C2PA_UUID + b"xx")) + mdat
    c["avif_meta_c2pa_uuid_prefix.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", b"\x01\x00\x00\x00" + C2PA_UUID)) + mdat
    c["avif_uuid_generated_by.avif"] = ftyp_avif + box(b"uuid", b"\x11" * 16 + b"Generated by AI tool") + mdat
    c["avif_uuid_plain.avif"] = ftyp_avif + box(b"uuid", b"\x22" * 16 + b"nothing here") + mdat
    c["avif_uuid_c2pa_marker.avif"] = ftyp_avif + box(b"uuid", b"\x33" * 16 + b"contentcredentials") + mdat
    c["avif_uuid_jumb_marker.avif"] = ftyp_avif + box(b"uuid", b"\x33" * 16 + b"jumb") + mdat
    c["avif_xmp_uuid_clean.avif"] = ftyp_avif + box(b"uuid", XMP_UUID + b"<x:xmpmeta/>") + mdat
    c["avif_xmp_uuid_contentauth.avif"] = ftyp_avif + box(b"uuid", XMP_UUID + b"<x/> contentauth") + mdat
    c["avif_xmp_uuid_openai.avif"] = ftyp_avif + box(b"uuid", XMP_UUID + b"<x/> OpenAI") + mdat
    c["avif_meta_xmp_clean.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", XMP_UUID + b"<x/>")) + mdat
    c["avif_meta_xmp_jumb.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", XMP_UUID + b"<x/> jumb")) + mdat
    c["avif_meta_uuid_marker.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", b"\x44" * 16 + b"Anthropic")) + mdat
    c["avif_meta_uuid_plain.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"uuid", b"\x44" * 16 + b"plain")) + mdat
    c["avif_meta_xml_openai.avif"] = ftyp_avif + fullbox(b"meta", hdlr + fullbox(b"xml ", b"<a>OpenAI</a>")) + mdat
    c["avif_meta_xml_plain.avif"] = ftyp_avif + fullbox(b"meta", hdlr + fullbox(b"xml ", b"<a/>")) + mdat
    c["avif_meta_bxml.avif"] = ftyp_avif + fullbox(b"meta", hdlr + fullbox(b"bxml", b"c2pa")) + mdat
    c["avif_meta_iinf_c2pa.avif"] = ftyp_avif + fullbox(b"meta", hdlr + fullbox(b"iinf", b"\x00\x01c2pa item")) + mdat
    c["avif_meta_iloc_marker.avif"] = ftyp_avif + fullbox(b"meta", hdlr + fullbox(b"iloc", b"ContentCredentials")) + mdat
    c["avif_meta_c2_subbox.avif"] = ftyp_avif + fullbox(b"meta", hdlr + box(b"c2xx", b"x") + box(b"jumb", b"y")) + mdat
    c["avif_meta_tiny.avif"] = ftyp_avif + box(b"meta", b"\x00\x00") + mdat
    c["avif_meta_empty.avif"] = ftyp_avif + box(b"meta", b"") + mdat
    c["avif_meta_tail_garbage.avif"] = ftyp_avif + fullbox(b"meta", hdlr + b"xyz") + mdat
    c["avif_toplevel_c2_type.avif"] = ftyp_avif + box(b"c2xx", b"manifest") + mdat
    c["avif_toplevel_C2_type.avif"] = ftyp_avif + box(b"C2PA", b"manifest") + mdat
    c["avif_largesize.avif"] = ftyp_avif + box64(b"jumb", b"c2pa 64-bit") + box64(b"mdat", b"pixels") + box(b"free", b"")
    c["avif_largesize_meta.avif"] = ftyp_avif + box64(b"meta", struct.pack(">I", 0) + hdlr + box64(b"uuid", XMP_UUID + b"xmp")) + mdat
    c["avif_size0_last.avif"] = ftyp_avif + fullbox(b"meta", hdlr) + struct.pack(">I", 0) + b"mdat" + b"rest of file c2pa"
    c["avif_size0_jumb.avif"] = ftyp_avif + struct.pack(">I", 0) + b"jumb" + b"\x00" * 10
    c["avif_truncated_mdat.avif"] = ftyp_avif + fullbox(b"meta", hdlr) + (mdat[:-5])
    c["avif_short_tail.avif"] = ftyp_avif + mdat + b"junk"
    c["avif_tail_8.avif"] = ftyp_avif + mdat + b"\x00\x00\x01\x00abcd"
    c["avif_truncated_c2pa_prov.avif"] = ftyp_avif + struct.pack(">I", 4000) + b"uuid" + C2PA_UUID + b"\x00" * 10
    c["avif_truncated_c2pa_ascii.avif"] = ftyp_avif + struct.pack(">I", 4000) + b"jumb" + b"c2pa data"
    c["avif_truncated_uuid_noprov.avif"] = ftyp_avif + struct.pack(">I", 4000) + b"uuid" + b"\x55" * 30
    c["avif_size_lt_header.avif"] = ftyp_avif + struct.pack(">I", 4) + b"mdat" + b"x" * 12
    c["avif_size_1_short.avif"] = ftyp_avif + struct.pack(">I", 1) + b"mdat" + b"x" * 4
    c["avif_first_overrun_c2pa.avif"] = struct.pack(">I", 200) + b"ftypavif" + b"\x00" * 8 + b"c2pa contentcredentials" + b"\x00" * 16
    c["avif_first_overrun_plain.avif"] = struct.pack(">I", 200) + b"ftypavif" + b"\x00" * 8 + b"nothing interesting" + b"\x00" * 16
    c["avif_ftyp_size_lt8.avif"] = struct.pack(">I", 4) + b"ftypavif" + b"\x00" * 20
    c["avif_mdat_marker_whole.avif"] = ftyp_avif + box(b"mdat", b"pixels c2pa pixels jumb")
    c["avis_brand.avif"] = box(b"ftyp", b"avis\x00\x00\x00\x00avis") + b"data"
    c["avio_brand.avif"] = box(b"ftyp", b"avio\x00\x00\x00\x00") + b"data" + b"\x00" * 8
    c["mif1_brand.heic"] = box(b"ftyp", b"mif1\x00\x00\x00\x00mif1heic") + b"data"
    c["heix_brand.heic"] = box(b"ftyp", b"heix\x00\x00\x00\x00") + b"datadata"
    c["msf1_brand.heic"] = box(b"ftyp", b"msf1\x00\x00\x00\x00") + b"datadata"
    c["heic_uuid_xmp_meta.heic"] = ftyp_heic + fullbox(b"meta", hdlr + box(b"uuid", XMP_UUID + b"<x digitalSourceType='trainedAlgorithmicMedia'/>")) + mdat
    c["heic_clean.heic"] = ftyp_heic + fullbox(b"meta", hdlr) + mdat
    c["ftyp_unknown_brand.bin"] = box(b"ftyp", b"mp42\x00\x00\x00\x00isom") + mdat
    c["ftyp_mp4_c2pa.bin"] = box(b"ftyp", b"isom\x00\x00\x00\x00isom") + box(b"uuid", C2PA_UUID + b"x") + mdat
    for name in ("sample_c2pa.avif", "sample_c2pa.heic"):
        c[f"fixture_{name}"] = (TESTS / "fixtures" / name).read_bytes()
    return c


def make_gif_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    mg = T_BGT._minimal_gif
    ext = T_BGT._gif_extension
    sub = T_BGT._gif_sub_block
    xmp = T_BGT.GIF_XMP
    c["gif_clean.gif"] = mg()
    c["gif_comment_c2pa_xmp.gif"] = mg((0xFE, b"made with c2pa tools"), (0xFF, xmp))
    c["gif_comment_plain.gif"] = mg((0xFE, b"just a comment"))
    c["gif_comment_openai.gif"] = mg((0xFE, b"OpenAI"))
    c["gif_xmp_clean.gif"] = mg((0xFF, b"XMP DataXMP<x/>"))
    c["gif_loop_gc.gif"] = mg(
        (0xFE, b"made with c2pa tools"),
        (0xFF, b"NETSCAPE2.0" + struct.pack("<H", 0)),
        (0xF9, b"\x00\x00\x00\x00"),
    )
    c["gif_icc_marker.gif"] = mg((0xFF, b"ICCRGBG1012" + b"AIGC"))
    c["gif_netscape_marker.gif"] = mg((0xFF, b"NETSCAPE2.0" + b"c2pa"))
    c["gif_app_c2pa.gif"] = mg((0xFF, b"c2pa_manifestXX"))
    c["gif_app_jumb_late.gif"] = mg((0xFF, b"abcdefghijkjumb"))
    c["gif_app_unknown.gif"] = mg((0xFF, b"MYAPPLICAT1.0data"))
    c["gif_app_unknown_marker.gif"] = mg((0xFF, b"MYAPPLICAT1.0 Claude"))
    c["gif_plaintext_ext.gif"] = mg((0x01, b"\x0c" + b"\x00" * 12 + b"hello"))
    lsd = struct.pack("<HHBBB", 2, 2, 0x91, 0, 0)
    gct = bytes(range(3 * (1 << ((0x91 & 7) + 1))))
    img2 = b"\x2c" + struct.pack("<HHHHB", 0, 0, 2, 2, 0x00) + b"\x02" + sub(2, b"\x02\x44") + b"\x00"
    c["gif_gct.gif"] = b"GIF89a" + lsd + gct + ext(0xFE, b"hello") + img2 + b"\x3b"
    lct_img = b"\x2c" + struct.pack("<HHHHB", 0, 0, 1, 1, 0x81) + bytes(6) + b"\x02" + sub(2, b"\x02\x44") + b"\x00"
    c["gif_lct.gif"] = mg((0xFE, b"c2pa"), image=lct_img)
    c["gif_87a.gif"] = b"GIF87a" + c["gif_clean.gif"][6:]
    c["gif_no_trailer.gif"] = c["gif_comment_c2pa_xmp.gif"][:-1]
    c["gif_junk_between.gif"] = b"GIF89a" + struct.pack("<HHBBB", 1, 1, 0, 0, 0) + b"\x99\x98" + ext(0xFE, b"x") + b"\x3b"
    c["gif_trailing_after_trailer.gif"] = c["gif_clean.gif"] + b"trailing c2pa"
    c["gif_trunc_ext.gif"] = b"GIF89a" + struct.pack("<HHBBB", 1, 1, 0, 0, 0) + b"\x21\xfe\x05ab"
    c["gif_trunc_ext_label.gif"] = b"GIF89a" + struct.pack("<HHBBB", 1, 1, 0, 0, 0) + b"\x21"
    c["gif_trunc_image.gif"] = b"GIF89a" + struct.pack("<HHBBB", 1, 1, 0, 0, 0) + b"\x2c\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x05ab"
    c["gif_trunc_image_hdr.gif"] = b"GIF89a" + struct.pack("<HHBBB", 1, 1, 0, 0, 0) + b"\x2c\x00\x00"
    c["gif_short_hdr.gif"] = b"GIF89a\x01\x00\x01"
    c["gif_hdr_only.gif"] = b"GIF89a"
    c["gif_gct_cut.gif"] = b"GIF89a" + lsd + gct[:10]
    c["gif_big_ext_payload.gif"] = mg((0xFE, b"A" * 600 + b"c2pa" + b"B" * 300))
    return c


def make_bmp_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    mb = T_BGT._minimal_bmp
    xmp = b'<x:xmpmeta><rdf:Description digitalSourceType="trainedAlgorithmicMedia"/></x:xmpmeta>'
    c["bmp_clean.bmp"] = mb()
    c["bmp_trailing_xmp.bmp"] = mb(trailing=xmp)
    c["bmp_trailing_plain.bmp"] = mb(trailing=b"trailing bytes without markers")
    c["bmp_trailing_openai.bmp"] = mb(trailing=b"<x:xmpmeta>OpenAI</x:xmpmeta>")
    c["bmp_trailing_c2pa.bmp"] = mb(trailing=b"c2pa jumb manifest and more and more")
    c["bmp_trailing_contentauth.bmp"] = mb(trailing=b"contentauth")
    base = bytearray(mb(trailing=b"OpenAI trailing"))

    def patch(off: int, fmt: str, val: int) -> bytes:
        b = bytearray(base)
        b[off : off + struct.calcsize(fmt)] = struct.pack(fmt, val)
        return bytes(b)

    c["bmp_rle_sizeimage.bmp"] = patch(30, "<I", 1)  # compression=RLE8, size_image=4
    c["bmp_bitfields_nosize.bmp"] = bytes(
        bytearray(patch(30, "<I", 3))[:34] + struct.pack("<I", 0) + bytes(base[38:])
    )
    c["bmp_neg_height.bmp"] = patch(22, "<i", -1)
    c["bmp_zero_height.bmp"] = patch(22, "<i", 0)
    c["bmp_neg_width.bmp"] = patch(18, "<i", -5)
    c["bmp_zero_bpp.bmp"] = patch(28, "<H", 0)
    c["bmp_huge_dims.bmp"] = bytes(
        bytearray(patch(18, "<i", 0x7FFFFFFF))[:22] + struct.pack("<i", -0x80000000) + bytes(base[26:28]) + struct.pack("<H", 0xFFFF) + bytes(base[30:])
    )
    c["bmp_dib_12.bmp"] = patch(14, "<I", 12)
    c["bmp_dib_huge.bmp"] = patch(14, "<I", 0xFFFFFFF0)
    c["bmp_pixel_off_past_end.bmp"] = patch(10, "<I", len(base) + 5)
    c["bmp_pixel_off_end.bmp"] = patch(10, "<I", len(base))
    c["bmp_v5_header.bmp"] = (
        b"BM" + struct.pack("<IHHI", 14 + 124 + 4, 0, 0, 14 + 124)
        + struct.pack("<IiiHHIIiiII", 124, 1, 1, 1, 32, 0, 4, 0, 0, 0, 0) + bytes(124 - 40) + b"\x00\x00\xff\xff" + b"c2pa!"
    )
    c["bmp_24bpp_pad.bmp"] = (
        b"BM" + struct.pack("<IHHI", 54 + 8, 0, 0, 54)
        + struct.pack("<IiiHHIIiiII", 40, 2, 1, 1, 24, 0, 0, 0, 0, 0, 0) + bytes(8) + b"Generated by AI"
    )
    c["bmp_len_20.bmp"] = base[:20]
    c["bmp_len_29.bmp"] = base[:29]
    c["bmp_len_14.bmp"] = base[:14]
    c["bmp_len_13.bmp"] = base[:13]
    c["bmp_bm_only.bmp"] = b"BM"
    c["bmp_truncated_pixels.bmp"] = base[:56]
    return c


def mk_tiff(ifds, little=True, big=False, extra_tail=b""):
    """Tiny TIFF builder. ifds: list of list of (tag, type, count, payload|int-offset-marker)."""
    bo = "<" if little else ">"
    off_len = 8 if big else 4
    count_len = 8 if big else 2
    entry_size = 20 if big else 12
    header_size = 16 if big else 8
    off_fmt = bo + ("Q" if big else "I")
    count_fmt = bo + ("Q" if big else "H")
    layout = []
    cursor = header_size
    ifd_offs = []
    for ents in ifds:
        ifd_offs.append(cursor)
        cursor += count_len + len(ents) * entry_size + off_len
    data_area = bytearray()
    base = cursor
    blocks = []
    for i, ents in enumerate(ifds):
        blk = bytearray(struct.pack(count_fmt, len(ents)))
        for tag, typ, count, payload in ents:
            if isinstance(payload, tuple):  # ("ptr", ifd_index)
                val = struct.pack(off_fmt, ifd_offs[payload[1]])
            elif len(payload) <= off_len:
                val = payload + b"\x00" * (off_len - len(payload))
            else:
                if len(data_area) & 1:
                    data_area.append(0)
                val = struct.pack(off_fmt, base + len(data_area))
                data_area.extend(payload)
            blk += struct.pack(bo + "HH", tag, typ) + struct.pack(off_fmt, count) + val
        nxt = ifd_offs[i + 1] if i + 1 < len(ifds) else 0
        blk += struct.pack(off_fmt, nxt)
        blocks.append(bytes(blk))
    magic = b"II" if little else b"MM"
    if big:
        hdr = magic + struct.pack(bo + "HHHQ", 43, 8, 0, ifd_offs[0])
    else:
        hdr = magic + struct.pack(bo + "HI", 42, ifd_offs[0])
    return hdr + b"".join(blocks) + bytes(data_area) + extra_tail


def make_tiff_cases() -> dict[str, bytes]:
    c: dict[str, bytes] = {}
    mt = T_BGT._minimal_tiff
    for name, kw in (
        ("le", {}),
        ("be", {"big_endian": True}),
        ("bigle", {"big": True}),
        ("bigbe", {"big": True, "big_endian": True}),
    ):
        c[f"tiff_{name}_meta.tif"] = mt(**kw)[0]
        c[f"tiff_{name}_clean.tif"] = mt(with_meta=False, **kw)[0]
    # cycle: IFD0's next pointer points at itself
    d = bytearray(mt()[0])
    cnt = struct.unpack("<H", d[8:10])[0]
    d[10 + cnt * 12 : 14 + cnt * 12] = struct.pack("<I", 8)
    c["tiff_cycle.tif"] = bytes(d)
    # chain of two IFDs with metadata in the second
    for big in (False, True):
        for little in (True, False):
            tag = ("big" if big else "le") + ("le" if little else "be")
            c[f"tiff_chain_{tag}.tif"] = mk_tiff(
                [
                    [(256, 4, 1, struct.pack("<I" if little else ">I", 1)), (305, 2, 4, b"abc\x00")],
                    [(270, 2, 20, b"Generated by AI tool\x00"), (65000, 2, 5, b"c2pa\x00"), (273, 4, 1, (b"c2pa" if True else b""))],
                ],
                little=little,
                big=big,
                extra_tail=b"tail",
            )
    c["tiff_marker_unknown_tag.tif"] = mk_tiff(
        [[(256, 4, 1, b"\x01\x00\x00\x00"), (65000, 2, 40, b"contentcredentials manifest here ok ok ok\x00"), (65001, 2, 3, b"ok\x00")]]
    )
    c["tiff_marker_keep_tag.tif"] = mk_tiff(
        [[(256, 4, 1, b"\x01\x00\x00\x00"), (273, 4, 4, b"c2pa" * 4), (279, 4, 1, b"\x08\x00\x00\x00")]]
    )
    c["tiff_xmp_only.tif"] = mk_tiff(
        [[(256, 4, 1, b"\x01\x00\x00\x00"), (700, 1, 30, b"<x:xmpmeta>plain xmp here</x:xmpmeta>")]]
    )
    c["tiff_software_aigc.tif"] = mk_tiff(
        [[(256, 4, 1, b"\x01\x00\x00\x00"), (305, 2, 12, b"AIGC tool 1\x00"), (306, 2, 5, b"2024\x00")]]
    )
    c["tiff_exif_subifd_marker.tif"] = mk_tiff(
        [
            [(256, 4, 1, b"\x01\x00\x00\x00"), (34665, 4, 1, ("ptr", 1))],
            [(37500, 7, 12, b"Anthropic mk\x00"), (36867, 2, 5, b"2024\x00")],
        ]
    )
    c["tiff_exif_subifd_clean.tif"] = mk_tiff(
        [
            [(256, 4, 1, b"\x01\x00\x00\x00"), (34665, 4, 1, ("ptr", 1))],
            [(36867, 2, 20, b"2024:01:01 00:00:00\x00")],
        ]
    )
    c["tiff_gps_subifd.tif"] = mk_tiff(
        [
            [(256, 4, 1, b"\x01\x00\x00\x00"), (34853, 4, 1, ("ptr", 1)), (40965, 4, 1, ("ptr", 2))],
            [(1, 2, 2, b"N\x00"), (2, 5, 3, b"x" * 24)],
            [(1, 2, 8, b"OpenAI!!!")],
        ]
    )
    c["tiff_nested_exif_gps.tif"] = mk_tiff(
        [
            [(256, 4, 1, b"\x01\x00\x00\x00"), (34665, 4, 1, ("ptr", 1))],
            [(36867, 2, 2, b"a\x00"), (34853, 4, 1, ("ptr", 2))],
            [(2, 5, 3, b"y" * 24)],
        ]
    )
    c["tiff_unknown_type.tif"] = mk_tiff([[(256, 4, 1, b"\x01\x00\x00\x00"), (65002, 99, 12, b"c2pa unknown!"), (65003, 2, 2, b"x\x00")]])
    c["tiff_keep_xp_tags.tif"] = mk_tiff([[(256, 4, 1, b"\x01\x00\x00\x00"), (40091, 1, 8, b"t\x00i\x00t\x00\x00\x00"), (33432, 2, 6, b"(c) me\x00")]])
    c["tiff_count_overflow.tif"] = b"II*\x00\x08\x00\x00\x00" + struct.pack("<H", 0xFFFF) + b"\x00" * 30
    c["tiff_big_count_overflow.tif"] = b"II+\x00\x08\x00\x00\x00" + struct.pack("<Q", 16) + struct.pack("<Q", 0xFFFFFFFFFFFFFFFF) + b"\x00" * 40
    c["tiff_first_zero.tif"] = b"II*\x00\x00\x00\x00\x00" + b"\x00" * 20
    c["tiff_first_past_end.tif"] = b"II*\x00\xff\xff\x00\x00" + b"\x00" * 20
    c["tiff_header_only.tif"] = b"II*\x00"
    c["tiff_header_only_8.tif"] = b"II*\x00\x08\x00\x00\x00"
    c["tiff_big_header_only.tif"] = b"MM\x00+\x00\x08\x00\x00"
    c["tiff_value_offset_past_end.tif"] = mk_tiff([[(256, 4, 1, b"\x01\x00\x00\x00"), (270, 2, 5, b"abcde")]])[:-3]
    c["tiff_truncated_entries.tif"] = mt()[0][:30]
    c["tiff_ifd_cut_next.tif"] = mt()[0][:8 + 2 + 11 * 12 + 1]
    return c


def make_misc_cases() -> dict[str, bytes]:
    rng = random.Random(7)
    return {
        "unknown_empty.bin": b"",
        "unknown_text.bin": b"hello world",
        "unknown_c2pa_text.bin": b"this text mentions c2pa and jumb",
        "unknown_random.bin": bytes(rng.randrange(256) for _ in range(96)),
        "unknown_ftyp_short.bin": b"\x00\x00\x00\x08ftyp",
        "unknown_svg.bin": b"<svg xmlns='http://www.w3.org/2000/svg'></svg>",
        "bm_two.bin": b"BM",
        "gif_sig_only.bin": b"GIF89a",
        "riff_not_webp.bin": b"RIFF\x04\x00\x00\x00WAVE",
        "ftyp_only.bin": b"\x00\x00\x00\x14ftypavif\x00\x00\x00\x00",
    }


# ---------------------------------------------------------------------------
# running the reference implementation
# ---------------------------------------------------------------------------


def err(e: BaseException) -> dict:
    return {"error": {"type": type(e).__name__, "msg": str(e)}}


def attempt(fn):
    try:
        return fn()
    except Exception as e:  # noqa: BLE001 -- recording Python behaviour
        return err(e)


INSPECTORS = {
    "png": im.inspect_png,
    "jpeg": im.inspect_jpeg,
    "webp": im.inspect_webp,
    "avif": lambda d: im.inspect_isobmff(d, "avif"),
    "heic": lambda d: im.inspect_isobmff(d, "heic"),
    "bmp": im.inspect_bmp,
    "gif": im.inspect_gif,
    "tiff": im.inspect_tiff,
}

STRIPPERS = {
    "png": lambda d, a: im.strip_png(d, strip_all_text=a),
    "jpeg": lambda d, a: im.strip_jpeg(d, strip_all_app=a),
    "webp": lambda d, a: im.strip_webp(d, strip_all_metadata=a),
    "avif": lambda d, a: im.strip_isobmff(d, "avif", strip_all_metadata=a),
    "heic": lambda d, a: im.strip_isobmff(d, "heic", strip_all_metadata=a),
    "bmp": lambda d, a: im.strip_bmp(d, strip_all_metadata=a),
    "gif": lambda d, a: im.strip_gif(d, strip_all_metadata=a),
    "tiff": lambda d, a: im.strip_tiff(d, strip_all_metadata=a),
}

TMP = Path(tempfile.mkdtemp(prefix="wm-image-gen-"))


def run_inspector(name, data):
    def go():
        c2pa, ai, findings = INSPECTORS[name](data)
        return {"has_c2pa": c2pa, "has_ai": ai, "findings": findings}

    return attempt(go)


def run_strip(name, data, strip_all):
    def go():
        out, actions = STRIPPERS[name](data, strip_all)
        return {"sha256": sha(out), "n": len(out), "actions": actions}

    return attempt(go)


def run_inspect_image(data):
    def go():
        src = TMP / "in.bin"
        src.write_bytes(data)
        r = im.inspect_image(src, data=data, run_synthid=False, include_exiftool=False).to_dict()
        return {
            "format": r["format"],
            "has_c2pa": r["has_c2pa"],
            "has_ai_metadata": r["has_ai_metadata"],
            "findings": r["findings"],
            "findings_confidence": r["findings_confidence"],
            "notes": r["notes"],
        }

    return attempt(go)


def run_clean(data, strip_all):
    def go():
        src = TMP / "c_in.bin"
        dest = TMP / "c_out.bin"
        if dest.exists():
            dest.unlink()
        src.write_bytes(data)
        r = im.clean_image(src, dest, strip_all_metadata=strip_all)
        out = dest.read_bytes()
        return {
            "format": r["format"],
            "actions": r["actions"],
            "bytes_in": r["bytes_in"],
            "bytes_out": r["bytes_out"],
            "changed": r["changed"],
            "still_has_c2pa": r["still_has_c2pa"],
            "still_has_ai_metadata": r["still_has_ai_metadata"],
            "post_findings": r["post_findings"],
            "sha256": sha(out),
        }

    return attempt(go)


def compact(r: dict) -> dict:
    """Fuzz cases omit fields that are pure functions of other recorded ones."""
    if "error" in r:
        return r
    return {k: v for k, v in r.items() if k not in ("actions", "findings_confidence", "format", "bytes_in")}


def run_case(data: bytes, full: bool) -> dict:
    res: dict = {"detect": im.detect_format(data), "inspect_image": run_inspect_image(data)}
    res["clean"] = {"all": run_clean(data, True), "keep": run_clean(data, False)}
    if not full:
        res["inspect_image"] = compact(res["inspect_image"])
        res["clean"] = {k: compact(v) for k, v in res["clean"].items()}
    if full:
        res["inspectors"] = {n: run_inspector(n, data) for n in INSPECTORS}
        res["strip"] = {
            f"{n}_{mode}": run_strip(n, data, mode == "all")
            for n in STRIPPERS
            for mode in ("all", "keep")
        }
    else:
        fmt = res["detect"]
        if fmt in INSPECTORS:
            res["inspectors"] = {fmt: run_inspector(fmt, data)}
            res["strip"] = {f"{fmt}_{m}": run_strip(fmt, data, m == "all") for m in ("all", "keep")}
        else:
            res["inspectors"] = {}
            res["strip"] = {}
    return res


def apply_spec(base: bytes, spec: dict) -> bytes:
    b = bytearray(base)
    for off, val in spec.get("edits", []):
        b[off] = val
    n = spec.get("len")
    return bytes(b[:n]) if n is not None else bytes(b)


# ---------------------------------------------------------------------------
# zlib differential cases
# ---------------------------------------------------------------------------


def zlib_outcome(data: bytes) -> dict:
    try:
        out = im._zlib_decompress_bounded(data)
        return {"ok": {"n": len(out), "sha256": sha(out)}}
    except im.PngTextBudgetExceeded:
        return {"budget": True}
    except zlib.error:
        return {"corrupt": True}


def make_zlib_cases() -> list[dict]:
    rng = random.Random(99)
    payloads = [
        b"",
        b"a",
        b"ChatGPT",
        b"Generated by AI " * 30,
        bytes(range(256)) * 3,
        b"abcabcabcabcabcabc" * 50 + b"tail",
        bytes(rng.randrange(256) for _ in range(300)),
        (b"The quick brown fox jumps over the lazy dog. " * 40),
    ]
    streams: list[tuple[str, bytes]] = []
    for pi, p in enumerate(payloads):
        for lvl in (0, 1, 6, 9):
            streams.append((f"p{pi}_l{lvl}", zlib.compress(p, lvl)))
        for strat_name, strat in (("fixed", zlib.Z_FIXED), ("huff", zlib.Z_HUFFMAN_ONLY), ("rle", zlib.Z_RLE)):
            co = zlib.compressobj(6, zlib.DEFLATED, 15, 8, strat)
            streams.append((f"p{pi}_{strat_name}", co.compress(p) + co.flush()))
        co = zlib.compressobj(6, zlib.DEFLATED, 15)
        parts = co.compress(p[: len(p) // 2]) + co.flush(zlib.Z_FULL_FLUSH) + co.compress(p[len(p) // 2 :]) + co.flush()
        streams.append((f"p{pi}_multi", parts))
    cases = []
    for name, s in streams:
        cases.append({"id": name, "hex": s.hex(), "expect": zlib_outcome(s)})
        # every prefix for short streams, a sample for long ones
        lens = range(len(s)) if len(s) <= 40 else sorted(set(rng.randrange(len(s)) for _ in range(10)))
        for k in lens:
            cases.append({"id": f"{name}_cut{k}", "hex": s[:k].hex(), "expect": zlib_outcome(s[:k])})
        for j in range(5):
            b = bytearray(s)
            for _ in range(rng.choice([1, 1, 2, 3])):
                if b:
                    b[rng.randrange(len(b))] = rng.choice([0, 0xFF, rng.randrange(256)])
            cases.append({"id": f"{name}_mut{j}", "hex": bytes(b).hex(), "expect": zlib_outcome(bytes(b))})
        extra = s + b"trailing garbage"
        cases.append({"id": f"{name}_trail", "hex": extra.hex(), "expect": zlib_outcome(extra)})
    # headers
    for hdr in (b"", b"\x78", b"\x78\x9c", b"\x78\x01", b"\x78\xda", b"\x08\x1d", b"\x78\xbb\x00\x00\x00\x00", b"\x78\xbb\x00\x00", b"\x78\xbb", b"\x79\x9c", b"\x68\x81", b"\x88\x1d", b"\x00\x00", b"\xff\xff"):
        cases.append({"id": f"hdr_{hdr.hex()}", "hex": hdr.hex(), "expect": zlib_outcome(hdr)})
    # random garbage behind a valid header
    for j in range(100):
        n = rng.randrange(1, 60)
        s = b"\x78\x9c" + bytes(rng.randrange(256) for _ in range(n))
        cases.append({"id": f"garbage{j}", "hex": s.hex(), "expect": zlib_outcome(s)})
    # budget boundaries
    for n in (1 << 20, (1 << 20) - 1, (1 << 20) + 1, 3 << 20):
        s = zlib.compress(b"\x00" * n, 9)
        cases.append({"id": f"zeros_{n}", "hex": s.hex(), "expect": zlib_outcome(s)})
        s2 = zlib.compress(bytes((i * 7) & 0xFF for i in range(n)), 1)
        cases.append({"id": f"pattern_{n}", "hex": s2.hex(), "expect": zlib_outcome(s2)})
        cases.append({"id": f"zeros_{n}_cut", "hex": s[:-6].hex(), "expect": zlib_outcome(s[:-6])})
    co = zlib.compressobj(0)
    stored = co.compress(b"\x01" * 70000) + co.flush()
    cases.append({"id": "stored_70000", "hex": stored.hex(), "expect": zlib_outcome(stored)})
    return cases


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    for old in DATA.iterdir():
        if old.is_file():
            old.unlink()

    bases: dict[str, bytes] = {}
    for fn in (make_png_cases, make_jpeg_cases, make_webp_cases, make_isobmff_cases, make_gif_cases, make_bmp_cases, make_tiff_cases, make_misc_cases):
        bases.update(fn())

    # All inputs are stored as files in tests/data; keep them small.
    LARGE = {n for n, b in bases.items() if len(b) > 20000}
    assert not LARGE, f"inputs too large to store: {sorted(LARGE)}"
    for name, data in bases.items():
        (DATA / name).write_bytes(data)

    cases = []
    for name, data in bases.items():
        cases.append({"id": name, "input": {"file": name}, "result": run_case(data, True)})

    # truncated prefixes + byte mutations derived from each base input
    fuzz = []
    for name, data in bases.items():
        rng = random.Random(zlib.crc32(name.encode()))
        n = len(data)
        cuts = {0, 3, 9, 17, n // 3, (2 * n) // 3, n - 1}
        cuts = sorted(c for c in cuts if 0 <= c < n)
        specs = [{"file": name, "len": c} for c in cuts]
        if n:
            for _ in range(2):
                edits = []
                for _ in range(rng.choice([1, 2, 3])):
                    edits.append([rng.randrange(n), rng.choice([0x00, 0xFF, 0x7F, 0x80, 0x01, rng.randrange(256)])])
                specs.append({"file": name, "edits": edits})
        for i, spec in enumerate(specs):
            mutated = apply_spec(data, spec)
            fuzz.append({"id": f"{name}#{i}", "input": spec, "result": run_case(mutated, False)})

    out = {
        "generator": "tests/gen_parity.py",
        "cases": cases,
        "fuzz": fuzz,
        "zlib": make_zlib_cases(),
    }
    (DATA / "parity.json").write_text(json.dumps(out, separators=(",", ":")) + "\n")

    nonvalue = {}
    for case in cases + fuzz:
        def walk(o):
            if isinstance(o, dict):
                if "error" in o and isinstance(o["error"], dict) and "type" in o["error"]:
                    t = o["error"]["type"]
                    if t != "ValueError":
                        nonvalue[t] = nonvalue.get(t, 0) + 1
                else:
                    for v in o.values():
                        walk(v)
        walk(case["result"])
    print(f"base cases: {len(cases)}  fuzz cases: {len(fuzz)}  zlib cases: {len(out['zlib'])}")
    print(f"non-ValueError python exceptions recorded: {nonvalue}")
    shutil.rmtree(TMP, ignore_errors=True)


if __name__ == "__main__":
    main()
