#!/usr/bin/env python3
"""Generate the Rust parity fixtures for wm-av.

Imports ``service/scripts/av_meta.py`` (the reference implementation), builds
synthetic MP4/MOV/WAV/MP3/FLAC inputs (written to ``tests/data/``) plus copies
of repo fixtures that sniff as an AV container, runs every inspector /
stripper / ``inspect_av`` / ``clean_av`` on them (and on truncated /
byte-mutated variants), and records the results -- with sha256 of every strip
output -- in ``tests/data/parity.json``. ``tests/parity.rs`` replays the same
inputs through the Rust crate and demands identical results.

Run from anywhere::

    python3 wasm/crates/wm-av/tests/gen_parity.py
"""

from __future__ import annotations

import hashlib
import json
import random
import shutil
import struct
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPO = HERE.parents[3]
sys.path.insert(0, str(REPO / "service" / "scripts"))
sys.path.insert(0, str(REPO / "tests"))

import av_meta as av  # noqa: E402
import image_meta as im  # noqa: E402
import test_av_meta as T  # noqa: E402

XMP = im.XMP_UUID
C2PA = im.C2PA_BMFF_UUID
sha = lambda b: hashlib.sha256(b).hexdigest()  # noqa: E731

box, xbox, mp4 = T._isobmff_box, T._extended_isobmff_box, T._mp4
frame, mp3, flac, geob = T._id3v2_frame, T._mp3, T._flac, T._c2pa_geob
riff, wav, ssz = T._riff_chunk, T._wav, T._id3v2_size_bytes
MDAT = box(b"mdat", b"\x00" * 16)
AUDIO = bytes([0xFF, 0xFB, 0x90, 0x00]) * 4


def id3_tag(major: int, body: bytes, flags: int = 0, footer: bool = False) -> bytes:
    f = b"3DI" + bytes([major, 0, flags]) + ssz(len(body)) if footer else b""
    return b"ID3" + bytes([major, 0, flags]) + ssz(len(body)) + body + f


def txxx(desc: bytes, val: bytes) -> bytes:
    return b"\x00" + desc + b"\x00" + val


def geob_enc(enc: int, mime: bytes, fn: bytes, desc: bytes, data: bytes) -> bytes:
    t = b"\x00" if enc in (0, 3) else b"\x00\x00"
    return bytes([enc]) + mime + b"\x00" + fn + t + desc + t + data


def flac_blocks(*blocks: tuple[int, bytes], last: int = 1) -> bytes:
    out = b"fLaC"
    for i, (t, p) in enumerate(blocks):
        h = t | (0x80 if i == len(blocks) - 1 and last else 0)
        out += bytes([h]) + len(p).to_bytes(3, "big") + p
    return out


def vorbis(*comments: bytes) -> bytes:
    v = b"ref libFLAC"
    o = struct.pack("<I", len(v)) + v + struct.pack("<I", len(comments))
    for c in comments:
        o += struct.pack("<I", len(c)) + c
    return o


STREAMINFO = (0, b"\x00" * 34)
inputs: dict[str, bytes] = {}


def add(name: str, data: bytes) -> None:
    assert name not in inputs, name
    inputs[name] = data


# ---------------- MP4 / MOV ----------------
XMP_AI = box(b"uuid", XMP + b"<x:xmpmeta>Generated by AI toolchain</x:xmpmeta>")
add("mp4_plain", mp4())
add("mp4_plain_mdat", mp4(MDAT))
add("mp4_xmp_ai", T._mp4_with_xmp(b"Generated by AI toolchain"))
add("mp4_xmp_clean", T._mp4_with_xmp(b"<x:xmpmeta>hello</x:xmpmeta>"))
add("mp4_xmp_c2pa_text", T._mp4_with_xmp(b"urn:c2pa:manifest contentauth"))
add("mp4_xmp_extended", mp4(xbox(b"uuid", XMP + b"Generated by AI"), MDAT))
add("mp4_udta_ai", T._mp4_with_udta_tag(b"Generated by AI"))
add("mp4_udta_c2pa", T._mp4_with_udta_tag(b"C2PA stuff jumb"))
add("mp4_udta_elevenlabs", T._mp4_with_udta_tag(b"ElevenLabs AI Voice Generator"))
add("mp4_udta_adobe", T._mp4_with_udta_tag(b"Adobe Premiere Pro 2026"))
add("mp4_udta_empty", mp4(T._moov_with_udta(b""), MDAT))
add("mp4_udta_two", mp4(box(b"moov", box(b"mvhd", b"\0" * 20) + box(b"udta", b"Claude") + box(b"udta", b"plain")), MDAT))
add("mp4_udta_ext_header", mp4(box(b"moov", xbox(b"udta", b"OpenAI Sora")), MDAT))
add("mp4_moov_ext", mp4(xbox(b"moov", box(b"mvhd", b"\0" * 20) + box(b"udta", b"SynthID")), MDAT))
add("mp4_c2pa_manifest", T._mp4_with_c2pa_manifest())
add("mp4_c2pa_binary", T._mp4_with_c2pa_manifest(data=bytes(range(1, 64))))
add("mp4_c2pa_merkle", T._mp4_with_c2pa_manifest(purpose=b"merkle", data=bytes(range(1, 128))))
add("mp4_c2pa_update", mp4(MDAT, box(b"uuid", C2PA + b"update\x00" + bytes(range(1, 32)))))
add("mp4_c2pa_off4", mp4(box(b"uuid", b"\0\0\0\0" + C2PA + b"manifest\x00data"), MDAT))
add("mp4_c2pa_off1_bad", mp4(box(b"uuid", b"\x00" + C2PA + b"not-a-manifest"), MDAT))
add("mp4_c2pa_meta_sub", mp4(box(b"meta", b"\0\0\0\0" + box(b"uuid", C2PA + b"manifest\0")), MDAT))
add("mp4_meta_xmp", mp4(box(b"meta", b"\0\0\0\0" + box(b"uuid", XMP + b"Generated by AI")), MDAT))
add("mp4_meta_xmp_clean", mp4(box(b"meta", b"\0\0\0\0" + box(b"uuid", XMP + b"hello")), MDAT))
add("mp4_meta_iinf", mp4(box(b"meta", b"\0\0\0\0" + box(b"iinf", b"c2pa item") + box(b"xml ", b"digitalSourceType")), MDAT))
add("mp4_meta_c2_sub", mp4(box(b"meta", b"\0\0\0\0" + box(b"c2xx", b"zz")), MDAT))
add("mp4_top_jumb", mp4(box(b"jumb", b"jumbf data"), MDAT))
add("mp4_top_c2pa_box", mp4(box(b"c2pa", b"manifest"), MDAT))
add("mp4_top_C2_box", mp4(box(b"C2xx", b"manifest"), MDAT))
add("mp4_uuid_plain", mp4(box(b"uuid", b"\x01" * 16 + b"plain"), MDAT))
add("mp4_uuid_marker", mp4(box(b"uuid", b"\x01" * 16 + b"contentcredentials"), MDAT))
add("mp4_uuid_generated_by", mp4(box(b"uuid", b"\x01" * 16 + b"Generated by tool"), MDAT))
add("mp4_size0_last", mp4(box(b"free", b"\0" * 8), b"\x00\x00\x00\x00mdat" + b"\x00" * 16))
add("mp4_size0_jumb", mp4(b"\x00\x00\x00\x00jumb" + b"x" * 8))
add("mp4_largesize_free", mp4(xbox(b"free", b"\0" * 8), MDAT))
media = bytearray(b"\x00" * 256)
media[32:36] = b"jumb"
media[64:84] = b"uuid" + C2PA
media[128:132] = b"JUMB"
add("mp4_chance_markers", mp4(box(b"free", b"\0" * 16), box(b"mdat", bytes(media)), T._moov_with_udta(b"Lavf/Remotion")))
add("mp4_c2pa_in_tail", mp4(MDAT) + b"\x00\x00\x00\x30uuid" + C2PA + b"x")  # truncated top-level box
add("mp4_tail_text_c2pa", mp4(MDAT) + b"\x00\x00\x00\x30xxxxc2pa")
whole = mp4(T._moov_with_udta(b"    toolGenerated by OpenAI Sora"), box(b"mdat", b"\x00" * 4096))
add("mp4_truncated_tail", whole[:-1024])
add("mp4_truncated_meta", mp4(T._moov_with_udta(b"    toolGenerated by OpenAI Sora" + b"\0" * 32))[:-16])
add("mp4_short_tail_7", mp4(MDAT) + b"\x01" * 7)
add("mov_qt", box(b"ftyp", b"qt  \x00\x00\x00\x00qt  ") + T._moov_with_udta(b"Claude") + MDAT)
add("m4a_brand", box(b"ftyp", b"M4A \x00\x00\x00\x00M4A mp42isom") + T._moov_with_udta(b"Anthropic") + MDAT)
add("m4v_brand", box(b"ftyp", b"M4V \x00\x00\x00\x00M4V mp42isom") + MDAT)
add("mp4_ftyp_only12", b"\x00\x00\x00\x0cftypisom")
add("mp4_ftyp_bad_size", b"\x00\x00\x00\x02ftypisom\x00\x00\x00\x00")
add("mp4_ftyp_hugesize", b"\xff\xff\xff\xffftypisom\x00\x00\x00\x00c2pa")
add("mp4_ftyp_size1_short", b"\x00\x00\x00\x01ftypisom")
for n in ("sample_c2pa.avif", "sample_c2pa.heic"):
    p = REPO / "tests" / "fixtures" / n
    if p.exists():
        add("fixture_" + n.replace(".", "_"), p.read_bytes())

# ---------------- ID3 / MP3 ----------------
TIT = frame(b"TIT2", b"\x00My Track")
TSSE = frame(b"TSSE", b"\x00Generated by AI")
add("mp3_clean_v23", mp3(TIT))
add("mp3_empty_tag", mp3())
add("mp3_ai_v23", mp3(TIT, TSSE))
add("mp3_ai_v24", mp3(frame(b"TIT2", b"\x00My Track", major=4), frame(b"TSSE", b"\x00Generated by AI", major=4), major=4))
add("mp3_ai_v24_flags", mp3(frame(b"TIT2", b"\x00My Track", major=4, flags=b"\x20\x00"), frame(b"TSSE", b"\x00OpenAI", major=4), major=4))
add("mp3_txxx_c2pa", mp3(TIT, frame(b"TXXX", txxx(b"c2pa", b"manifest"))))
add("mp3_priv_c2pa", mp3(frame(b"PRIV", b"c2pa\x00" + b"\x01" * 20), TIT))
add("mp3_priv_contentauth", mp3(frame(b"PRIV", b"owner\x00ContentAuthX"), TIT))
add("mp3_geob_c2pa", mp3(TIT, frame(b"GEOB", geob())))
add("mp3_geob_c2pa_v24", mp3(frame(b"GEOB", geob(), major=4), major=4))
add("mp3_all_ai", mp3(TSSE, frame(b"TXXX", txxx(b"c2pa", b"x"))))
add("mp3_latin1_frameid", mp3(frame(b"T\xe9ST", b"\x00Claude"), TIT))
add("mp3_padding", mp3(TIT, TSSE, b"\x00" * 24))
add("mp3_padding_only_after_clean", mp3(TIT, b"\x00" * 24))
add("mp3_ext_hdr_v23", id3_tag(3, struct.pack(">I", 6) + b"\x80\x00\x00\x00\x00\x00" + TIT + TSSE, flags=0x40) + AUDIO)
add("mp3_ext_hdr_v24", id3_tag(4, ssz(6) + b"\x01\x00" + frame(b"TIT2", b"\x00x", major=4) + frame(b"TSSE", b"\x00OpenAI", major=4), flags=0x40) + AUDIO)
add("mp3_ext_hdr_bad", id3_tag(3, struct.pack(">I", 500) + b"\0" * 6, flags=0x40) + AUDIO)
add("mp3_ext_hdr_tiny_body", id3_tag(3, b"\0\0", flags=0x40) + AUDIO)
add("mp3_footer_v24", id3_tag(4, frame(b"TIT2", b"\x00x", major=4) + frame(b"TSSE", b"\x00Claude", major=4), flags=0x10, footer=True) + AUDIO)
add("mp3_footer_bad", id3_tag(4, frame(b"TIT2", b"\x00x", major=4), flags=0x10, footer=False) + b"\x00" * 10 + AUDIO)
add("mp3_footer_flag_v23", id3_tag(3, TIT + TSSE, flags=0x10) + AUDIO)
add("mp3_v22_ai", id3_tag(2, b"TT2\x00\x00\x10\x00Generated by AI") + AUDIO)
add("mp3_v22_clean", id3_tag(2, b"TT2\x00\x00\x07\x00My Song") + AUDIO)
add("mp3_v22_c2pa", id3_tag(2, b"CRM\x00\x00\x10c2pa") + AUDIO)
add("mp3_v25", id3_tag(5, TIT + TSSE) + AUDIO)
add("mp3_v21", id3_tag(1, b"junk Claude") + AUDIO)
add("mp3_bad_frame_size", mp3(TSSE, b"TIT2" + struct.pack(">I", 200) + b"\0\0partial"))
add("mp3_nonzero_tail", mp3(TSSE, b"TIT2bad"))
add("mp3_short_zero_tail", mp3(TSSE, b"\x00" * 7))
add("mp3_zero_size_frame", mp3(frame(b"TXXX", b""), TSSE))
add("mp3_syncsafe_bad", b"ID3\x03\x00\x00\x80\x00\x00\x00" + AUDIO)
add("mp3_sync_only", AUDIO * 5)
add("mp3_sync_c2pa_text", AUDIO + b"c2pa" + AUDIO)
add("mp3_id3_then_flac", id3_tag(3, TIT) + b"fLaC" + b"\x80\x00\x00\x22" + b"\0" * 34)
add("mp3_tag_only", id3_tag(3, TIT + TSSE))
add("mp3_hdr_only", b"ID3\x03\x00\x00\x00\x00\x00\x00")
body = TIT + TSSE
trunc_tag = b"ID3\x03\x00\x00" + ssz(len(body) + 500) + body
add("mp3_trunc_tag_audio", trunc_tag + AUDIO)
add("mp3_trunc_tag_noaudio", trunc_tag + b"\x00" * 6)
add("mp3_trunc_tag_ai_noaudio", b"ID3\x03\x00\x00" + ssz(900) + b"\x00TXXX" + b"c2pa" + b"\x01" * 12)
add("mp3_trunc_tag_ai_audio", b"ID3\x04\x00\x00" + ssz(900) + b"\x00TXXX" + b"Claude" + AUDIO)
for i, (b1, b2, b3) in enumerate([(0xFB, 0x90, 0x00), (0xE9, 0x90, 0), (0xF9, 0x90, 0), (0xFB, 0x00, 0), (0xFB, 0xF0, 0), (0xFB, 0x9C, 0), (0xFB, 0x90, 0x02), (0xF3, 0x50, 0x01), (0xE3, 0x10, 0x00)]):
    add(f"mp3_trunc_tag_hdr{i}", b"ID3\x03\x00\x00" + ssz(4000) + b"\x01\x02\x03" + bytes([0xFF, b1, b2, b3]) + b"\x00" * 8)
add("mp3_trunc_sync_at_end", b"ID3\x03\x00\x00" + ssz(4000) + b"\x01\x02\xff\xfb\x90")

# ---------------- FLAC ----------------
add("flac_plain", flac())
add("flac_geob", flac(frame(b"GEOB", geob())))
add("flac_title_geob", flac(TIT, frame(b"GEOB", geob())))
add("flac_geob_title_v24", flac(frame(b"TIT2", b"\x00My Track", major=4, flags=b"\x20\x00"), frame(b"GEOB", geob(), major=4), major=4))
add("flac_title_only", flac(TIT))
add("flac_ai_text_only", flac(frame(b"COMM", b"\x00Generated by AI")))
add("flac_geob_trunc", flac(frame(b"GEOB", b"\x00application/c2pa\x00")))
v23x = struct.pack(">I", 10) + b"\x80\x00" + struct.pack(">I", 0) + b"\x00" * 4
v24x = ssz(6) + b"\x01\x00"
add("flac_ext_v23", flac(TIT, frame(b"GEOB", geob()), major=3, extended_header=v23x))
add("flac_ext_v24", flac(frame(b"TIT2", b"\x00My Track", major=4), frame(b"GEOB", geob(), major=4), major=4, extended_header=v24x))
add("flac_footer_v24", flac(frame(b"TIT2", b"\x00My Track", major=4), frame(b"GEOB", geob(), major=4), major=4, footer=True))
add("flac_ext_and_footer", flac(frame(b"TIT2", b"\x00x", major=4), frame(b"GEOB", geob(), major=4), major=4, extended_header=v24x, footer=True))
add("flac_trunc_frame", flac(frame(b"GEOB", geob()), b"TIT2" + struct.pack(">I", 20) + b"\0\0partial"))
add("flac_nonzero_tail", flac(frame(b"GEOB", geob()), b"TIT2bad"))
add("flac_zero_pad", flac(frame(b"GEOB", geob()), b"\x00" * 7))
add("flac_two_geob", flac(frame(b"GEOB", geob()), TIT, frame(b"GEOB", geob())))
add("flac_geob_noncp", flac(frame(b"GEOB", geob_enc(0, b"application/octet-stream", b"f", b"d", b"data"))))
add("flac_geob_upper_mime", flac(frame(b"GEOB", geob_enc(0, b"Application/C2PA", b"f.c2pa", b"d", b"data"))))
add("flac_geob_utf16", flac(frame(b"GEOB", geob_enc(1, b"application/c2pa", b"f\x00".replace(b"\x00", b"") + b"\x00", b"d\x00", b"data"))))
add("flac_geob_utf16_ok", flac(frame(b"GEOB", b"\x01application/c2pa\x00" + b"f\x00\x00\x00" + b"d\x00\x00\x00" + b"data")))
add("flac_geob_utf16be", flac(frame(b"GEOB", b"\x02application/c2pa\x00" + b"\x00f\x00\x00" + b"\x00d\x00\x00" + b"data")))
add("flac_geob_utf8_enc3", flac(frame(b"GEOB", geob_enc(3, b"application/c2pa", b"f", b"d", b"data"))))
add("flac_geob_enc4", flac(frame(b"GEOB", geob_enc(4, b"application/c2pa", b"f", b"d", b"data"))))
add("flac_geob_desc_at_end", flac(frame(b"GEOB", b"\x00application/c2pa\x00f\x00d\x00")))
add("flac_geob_empty", flac(frame(b"GEOB", b"")))
add("flac_native_vorbis_ai", flac_blocks(STREAMINFO, (4, vorbis(b"TITLE=x", b"COMMENT=Generated by AI c2pa")), (1, b"\0" * 8)))
add("flac_native_application", flac_blocks(STREAMINFO, (2, b"c2pa" + b"\x01" * 16), (6, b"\x00\x00\x00\x03image/png\x00" + b"\x00" * 24)))
add("flac_id3_native", id3_tag(3, TIT + frame(b"GEOB", geob())) + flac_blocks(STREAMINFO, (4, vorbis(b"A=B")), (6, b"\0" * 32)))
add("flac_id3_native_clean", id3_tag(3, TIT) + flac_blocks(STREAMINFO, (4, vorbis(b"A=B"))))
add("flac_sig_only", b"fLaC")
add("flac_id3_trunc", b"ID3\x03\x00\x00" + ssz(300) + TIT + b"fLaC")
add("flac_id3_empty_tag", b"ID3\x03\x00\x00\x00\x00\x00\x00fLaC" + b"\x80\x00\x00\x22" + b"\0" * 34)

# ---------------- WAV ----------------
FMT, DATA_CH = T._wav_fmt_chunk(), T._wav_data_chunk()
info = T._wav_list_info
add("wav_plain", wav(FMT, DATA_CH))
add("wav_info_ai", wav(FMT, info(b"Generated by AI"), DATA_CH))
add("wav_info_ai_odd", wav(FMT, info(b"Generated by AI!"), DATA_CH))
add("wav_info_clean", wav(FMT, info(b"Adobe Audition"), DATA_CH))
add("wav_info_c2pa", wav(FMT, info(b"C2PA content"), DATA_CH))
add("wav_info_contentcred", wav(FMT, info(b"ContentCredentials"), DATA_CH))
add("wav_info_claude", wav(FMT, info(b"Claude"), DATA_CH))
add("wav_list_adtl", wav(FMT, riff(b"LIST", b"adtl" + b"Generated by AI"), DATA_CH))
add("wav_ixml_ai", wav(FMT, riff(b"iXML", b"<BWFXML>Generated by AI</BWFXML>"), DATA_CH))
add("wav_pmx_xmp", wav(FMT, riff(b"_PMX", b"<x:xmpmeta>c2pa digitalSourceType</x:xmpmeta>"), DATA_CH))
add("wav_c2pa_chunk", wav(FMT, riff(b"C2PA", b"C2PA manifest store"), DATA_CH))
add("wav_c2pa_chunk_odd", wav(FMT, riff(b"C2PA", b"odd"), DATA_CH))
add("wav_c2pa_lower", wav(FMT, riff(b"c2pa", b"manifest"), DATA_CH))
add("wav_c2pa_last", wav(FMT, DATA_CH, riff(b"C2PA", b"manifest!")))
add("wav_id3_ai", wav(FMT, riff(b"id3 ", mp3(TIT, TSSE)[:-16]), DATA_CH))
add("wav_id3_c2pa_txxx", wav(FMT, riff(b"id3 ", id3_tag(3, frame(b"TXXX", txxx(b"c2pa", b"m")))), DATA_CH))
add("wav_id3_clean", wav(FMT, riff(b"id3 ", id3_tag(3, TIT)), DATA_CH))
add("wav_ID3_upper", wav(FMT, riff(b"ID3 ", id3_tag(3, TIT + TSSE)), DATA_CH))
add("wav_id3_v22_ai", wav(FMT, riff(b"id3 ", id3_tag(2, b"TT2\x00\x00\x10\x00Generated by AI")), DATA_CH))
add("wav_id3_trunc_ai", wav(FMT, riff(b"id3 ", b"ID3\x03\x00\x00" + ssz(900) + b"\x00TXXX c2pa"), DATA_CH))
add("wav_id3_trunc_clean", wav(FMT, riff(b"id3 ", b"ID3\x03\x00\x00" + ssz(900) + b"\x00TXXX nothing"), DATA_CH))
add("wav_multi_meta", wav(FMT, info(b"Generated by AI"), riff(b"C2PA", b"x"), riff(b"id3 ", id3_tag(3, TIT)), DATA_CH))
add("wav_chunk_overrun", wav(FMT, DATA_CH)[:-3] if False else wav(FMT) + b"data" + struct.pack("<I", 1000) + b"\x01" * 10)
add("wav_chunk_huge", wav(FMT, DATA_CH) + b"junk" + struct.pack("<I", 0xFFFFFFFF) + b"zz")
add("wav_trailing_5", wav(FMT, DATA_CH) + b"\x01" * 5)
add("wav_trailing_8", wav(FMT, DATA_CH) + b"\x01" * 8)
add("wav_riff_size_wrong", b"RIFF\x00\x00\x00\x00WAVE" + FMT + info(b"Claude") + DATA_CH)
add("wav_header_only", b"RIFF\x04\x00\x00\x00WAVE")
add("wav_odd_pad_last_missing", wav(FMT, info(b"Claude"))[:-1] if False else b"RIFF\x00\x00\x00\x00WAVE" + riff(b"odd ", b"abc")[:-1])
add("wav_info_pad_missing", b"RIFF\x00\x00\x00\x00WAVE" + riff(b"LIST", b"INFOGenerated by AI.")[:-1] + b"")
add("wav_rf64_like", b"RF64\xff\xff\xff\xffWAVE" + FMT + DATA_CH)
add("wav_info_empty", wav(FMT, riff(b"LIST", b"INFO"), DATA_CH))
add("wav_list_short", wav(FMT, riff(b"LIST", b"IN"), DATA_CH))

# ---------------- misc ----------------
add("unknown_empty", b"")
add("unknown_text", b"not a known av container")
add("unknown_c2pa_text", b"c2pa jumb Generated by AI")
add("unknown_random", bytes(random.Random(7).randrange(256) for _ in range(96)))
add("unknown_riff_notwave", b"RIFF\x04\x00\x00\x00AVI LIST")
add("unknown_ftyp_short", b"\x00\x00\x00\x08ftyp")
add("unknown_id3_short", b"ID3\x03\x00")
add("unknown_ff_one", b"\xff")
add("unknown_ff_e0", b"\xff\xe0")
add("unknown_ff_c0", b"\xff\xc0\x00")

# ---------------- run reference ----------------


def exc(e: Exception) -> dict:
    return {"error": {"type": type(e).__name__, "msg": str(e)}}


def inspect_dict(d: bytes) -> dict:
    r = av.inspect_av(Path("x.bin"), data=d).to_dict()
    del r["path"]
    return r


def clean(d: bytes, all_: bool) -> dict:
    with tempfile.TemporaryDirectory() as td:
        src, dst = Path(td) / "in.bin", Path(td) / "out.bin"
        src.write_bytes(d)
        try:
            r = av.clean_av(src, dst, strip_all_metadata=all_)
        except Exception as e:  # noqa: BLE001
            return exc(e)
        out = dst.read_bytes()
    for k in ("input", "output"):
        r.pop(k)
    r["sha"] = sha(out)
    return r


def call(fn, *a, **k):
    try:
        return fn(*a, **k)
    except Exception as e:  # noqa: BLE001
        return exc(e)


def ins(t):
    return {"c2pa": t[0], "ai": t[1], "findings": t[2]}


def strip_res(fn, d, all_, extra=False):
    try:
        r = fn(d, strip_all_metadata=all_)
    except Exception as e:  # noqa: BLE001
        return exc(e)
    o = {"sha": sha(r[0]), "len": len(r[0]), "actions": r[1]}
    if extra:
        o["incomplete"] = r[2]
    return o


def parse_res(d):
    try:
        p = av._parse_id3v2_frames(d)
    except Exception as e:  # noqa: BLE001
        return exc(e)
    if p is None:
        return None
    return {"total": p[0], "major": p[1], "frames": [[fid.hex(), sha(pl), len(pl)] for fid, pl in p[2]]}


def record(d: bytes, full: bool) -> dict:
    r = {
        "detect": av.detect_av_format(d),
        "inspect": call(inspect_dict, d),
        "clean_all": clean(d, True),
        "clean_keep": clean(d, False),
    }
    if full:
        r["direct"] = {
            "parse_id3": parse_res(d),
            "inspect_id3v2": call(lambda: ins(av._inspect_id3v2(d))),
            "inspect_mp4": call(lambda: ins(av._inspect_mp4(d))),
            "inspect_wav": call(lambda: ins(av._inspect_wav(d))),
            "inspect_flac": call(lambda: ins(av._inspect_flac(d))),
            "inspect_udta": call(lambda: ins(av._inspect_moov_udta(d))),
            "strip_id3v2": [strip_res(av._strip_id3v2, d, a) for a in (True, False)],
            "strip_mp4": [strip_res(av._strip_mp4, d, a, True) for a in (True, False)],
            "strip_wav": [strip_res(av._strip_wav, d, a) for a in (True, False)],
            "strip_flac": [strip_res(av._strip_flac, d, a) for a in (True, False)],
            "strip_udta": [strip_res(av._strip_moov_udta, d, a, True) for a in (True, False)],
        }
    return r


def main() -> None:
    if DATA.exists():
        shutil.rmtree(DATA)
    DATA.mkdir()
    rng = random.Random(20260604)
    cases = []
    for name, d in inputs.items():
        fn = name + ".bin"
        (DATA / fn).write_bytes(d)
        cases.append({"name": name, "file": fn, **record(d, True)})
        n = len(d)
        lens = sorted({k for k in (3, 8, 11, 12, 20, 36) if k < n})
        lens += sorted({rng.randrange(1, n) for _ in range(2)} - set(lens)) if n > 1 else []
        for k in lens:
            cases.append({"name": f"{name}@len{k}", "file": fn, "len": k, **record(d[:k], False)})
        for j in range(3):
            b = bytearray(d)
            edits = []
            for _ in range(rng.choice((1, 1, 2))):
                if not b:
                    break
                off = rng.randrange(min(len(b), 48)) if j % 2 == 0 else rng.randrange(len(b))
                val = rng.choice((0x00, 0xFF, 0x7F, 0x80, rng.randrange(256)))
                b[off] = val
                edits.append([off, val])
            if edits:
                cases.append({"name": f"{name}@mut{j}", "file": fn, "edits": edits, **record(bytes(b), False)})
    out = {"cases": cases}
    (DATA / "parity.json").write_text(json.dumps(out, separators=(",", ":")) + "\n")
    print(len(inputs), "inputs,", len(cases), "cases,", (DATA / "parity.json").stat().st_size, "bytes json")


if __name__ == "__main__":
    main()
