//! Helpers shared by every format module, and intended for reuse by the later
//! av/container crates (ports of the needle tables, `_contains_any`, and
//! `classify_finding_confidence` from `service/scripts/{image_meta,common}.py`).

use std::fmt;

/// Error raised where the Python code raises `ValueError`. The message is the
/// exact Python message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageError(pub String);

impl ImageError {
    pub fn new(msg: impl Into<String>) -> Self {
        ImageError(msg.into())
    }
}

impl fmt::Display for ImageError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for ImageError {}

/// `(has_c2pa, has_ai_metadata, findings)` as returned by every `inspect_*`.
pub type Inspection = (bool, bool, Vec<String>);
/// `(cleaned_bytes, actions)` as returned by every `strip_*`.
pub type Stripped = Result<(Vec<u8>, Vec<String>), ImageError>;

pub const PNG_SIG: &[u8] = b"\x89PNG\r\n\x1a\n";
pub const JPEG_SOI: &[u8] = b"\xff\xd8";
pub const WEBP_RIFF: &[u8] = b"RIFF";
pub const WEBP_SIG: &[u8] = b"WEBP";
pub const BMP_SIG: &[u8] = b"BM";
pub const GIF_SIGS: [&[u8]; 2] = [b"GIF87a", b"GIF89a"];
pub const TIFF_LE_SIG: &[u8] = b"II*\x00";
pub const TIFF_BE_SIG: &[u8] = b"MM\x00*";
pub const TIFF_LE_BIG_SIG: &[u8] = b"II+\x00";
pub const TIFF_BE_BIG_SIG: &[u8] = b"MM\x00+";

/// Chunk types / content patterns associated with C2PA / AI provenance.
pub const C2PA_MARKERS: [&[u8]; 9] = [
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/",
];

pub const AI_META_HINTS: [&[u8]; 17] = [
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
];

/// Unambiguous provenance markers usable against free-text JPEG COM.
pub const JPEG_C2PA_MARKERS: [&[u8]; 5] =
    [b"c2pa", b"c2ma", b"contentcredentials", b"contentauth", b"cai:"];

/// `JPEG_COM_AI_HINTS` of the Python source (`*JPEG_C2PA_MARKERS` + extras).
pub const JPEG_COM_AI_HINTS: [&[u8]; 14] = [
    b"c2pa",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"AI generated",
    b"Generated by AI",
    b"SynthID",
    b"dcterms:provenance",
];

/// Well-known AI generator product names, matched only against generator
/// text-chunk keys (see [`crate::png::generator_product_hits`]).
pub const AI_GENERATOR_PRODUCTS: [&[u8]; 31] = [
    b"ChatGPT",
    b"DALL-E",
    b"Midjourney",
    b"Stable Diffusion",
    b"SDXL",
    b"FLUX",
    b"DreamStudio",
    b"Leonardo AI",
    b"Leonardo.Ai",
    b"Craiyon",
    b"NovelAI",
    b"Ideogram",
    b"TensorArt",
    b"Recraft",
    b"Clipdrop",
    b"DeepAI",
    b"NightCafe",
    b"Bing Image Creator",
    b"Adobe Firefly",
    b"Firefly",
    b"Gemini",
    b"Imagen",
    b"Grok",
    b"Sora",
    b"Veo",
    b"Kling",
    b"Runway",
    b"Luma",
    b"Qwen",
    b"GPT-4",
    b"GPT-5",
];

/// PNG text-chunk keys whose value can name the generating model/tool.
pub const GENERATOR_TEXT_KEYS: [&str; 3] = ["software", "creator", "parameters"];

/// `AI_META_HINTS + C2PA_MARKERS`, the combined table used almost everywhere.
pub fn ai_and_c2pa_needles() -> Vec<&'static [u8]> {
    let mut v: Vec<&'static [u8]> = AI_META_HINTS.to_vec();
    v.extend_from_slice(&C2PA_MARKERS);
    v
}

/// First index of `needle` in `hay` at or after `start`.
pub fn find_subslice_from(hay: &[u8], needle: &[u8], start: usize) -> Option<usize> {
    if start > hay.len() {
        return None;
    }
    if needle.is_empty() {
        return Some(start);
    }
    if needle.len() > hay.len() - start {
        return None;
    }
    let first = needle[0];
    let last_start = hay.len() - needle.len();
    let mut i = start;
    while i <= last_start {
        let p = hay[i..=last_start].iter().position(|&b| b == first)?;
        i += p;
        if &hay[i..i + needle.len()] == needle {
            return Some(i);
        }
        i += 1;
    }
    None
}

pub fn find_subslice(hay: &[u8], needle: &[u8]) -> Option<usize> {
    find_subslice_from(hay, needle, 0)
}

/// Python `needle in blob` for bytes.
pub fn contains_bytes(hay: &[u8], needle: &[u8]) -> bool {
    find_subslice(hay, needle).is_some()
}

/// Decode ASCII with `errors="replace"` (non-ASCII byte becomes U+FFFD).
pub fn ascii_replace(b: &[u8]) -> String {
    b.iter().map(|&c| if c < 0x80 { c as char } else { '\u{fffd}' }).collect()
}

/// Decode bytes as latin-1 (every byte maps to the same code point).
pub fn latin1(b: &[u8]) -> String {
    b.iter().map(|&c| c as char).collect()
}

/// Port of `_contains_any`: needle labels (in needle order) whose
/// ASCII-lowercased form occurs in the ASCII-lowercased blob.
pub fn contains_any(blob: &[u8], needles: &[&[u8]]) -> Vec<String> {
    contains_any_groups(blob, &[needles])
}

/// `_contains_any(blob, a + b + ...)` without building the concatenation.
pub fn contains_any_groups(blob: &[u8], groups: &[&[&[u8]]]) -> Vec<String> {
    let lower = blob.to_ascii_lowercase();
    let mut found = Vec::new();
    for group in groups {
        for n in group.iter() {
            let nl = n.to_ascii_lowercase();
            if !nl.is_empty() && find_subslice(&lower, &nl).is_some() {
                found.push(ascii_replace(n));
            }
        }
    }
    found
}

/// `_contains_any(blob, AI_META_HINTS + C2PA_MARKERS)`.
pub fn contains_ai_or_c2pa(blob: &[u8]) -> Vec<String> {
    contains_any_groups(blob, &[&AI_META_HINTS, &C2PA_MARKERS])
}

/// `bool(_contains_any(...))` shortcut for the combined table.
pub fn has_ai_or_c2pa(blob: &[u8]) -> bool {
    !contains_ai_or_c2pa(blob).is_empty()
}

/// `any(h.lower() in set for h in hits)`.
pub fn any_lower_in(hits: &[String], set: &[&str]) -> bool {
    hits.iter().any(|h| {
        let l = h.to_lowercase();
        set.iter().any(|s| *s == l)
    })
}

/// `", ".join(hits[:n])`.
pub fn join_first(hits: &[String], n: usize) -> String {
    hits.iter().take(n).cloned().collect::<Vec<_>>().join(", ")
}

/// Python `repr()` of a bytes object (used in the "truncated chunk b'IDAT'"
/// finding).
pub fn py_bytes_repr(b: &[u8]) -> String {
    let has_sq = b.contains(&b'\'');
    let has_dq = b.contains(&b'"');
    let quote = if has_sq && !has_dq { b'"' } else { b'\'' };
    let mut s = String::with_capacity(b.len() + 3);
    s.push('b');
    s.push(quote as char);
    for &c in b {
        match c {
            b'\\' => s.push_str("\\\\"),
            b'\t' => s.push_str("\\t"),
            b'\n' => s.push_str("\\n"),
            b'\r' => s.push_str("\\r"),
            c if c == quote => {
                s.push('\\');
                s.push(c as char);
            }
            0x20..=0x7e => s.push(c as char),
            _ => s.push_str(&format!("\\x{c:02x}")),
        }
    }
    s.push(quote as char);
    s
}

/// Bounds-checked big/little-endian readers (never panic).
pub fn rd_u16(data: &[u8], at: usize, little: bool) -> Option<u16> {
    let b: [u8; 2] = data.get(at..at.checked_add(2)?)?.try_into().ok()?;
    Some(if little { u16::from_le_bytes(b) } else { u16::from_be_bytes(b) })
}

pub fn rd_u32(data: &[u8], at: usize, little: bool) -> Option<u32> {
    let b: [u8; 4] = data.get(at..at.checked_add(4)?)?.try_into().ok()?;
    Some(if little { u32::from_le_bytes(b) } else { u32::from_be_bytes(b) })
}

pub fn rd_u64(data: &[u8], at: usize, little: bool) -> Option<u64> {
    let b: [u8; 8] = data.get(at..at.checked_add(8)?)?.try_into().ok()?;
    Some(if little { u64::from_le_bytes(b) } else { u64::from_be_bytes(b) })
}

/// Python `data[a:b]` (clamped, never panics; empty when `a >= b`).
pub fn slice_clamped(data: &[u8], a: usize, b: usize) -> &[u8] {
    let b = b.min(data.len());
    if a >= b {
        &[]
    } else {
        &data[a..b]
    }
}

pub const CONFIDENCE_LEVELS: [&str; 4] =
    ["confirmed", "probable", "informational", "likely_false_positive"];

/// Port of `common.classify_finding_confidence`.
pub fn classify_finding_confidence(finding: &str) -> &'static str {
    let t = finding.to_lowercase();

    if t.starts_with("layer-a") && t.ends_with("(space)") {
        return "informational";
    }

    const CONFIRMED: [&str; 12] = [
        "c2patool reports",
        "c2pa-related manifest",
        "png chunk c2",
        "png chunk cabx",
        "png chunk jumb",
        "png chunk jumd",
        "jpeg app11 segment",
        "digital_source_type",
        "digitalsourcetype",
        "trainedalgorithmicmedia",
        "compositewithtrainedalgorithmicmedia",
        "softwareagent",
    ];
    if CONFIRMED.iter().any(|s| t.contains(s)) {
        return "confirmed";
    }

    const INFORMATIONAL: [&str; 11] = [
        "cms generator",
        "customxml parts",
        "xmp packet present",
        "unsupported",
        "not fully inspected",
        "format not",
        "svg <metadata> present",
        "not a valid",
        "truncated chunk",
        "bad segment length",
        "svg decode note",
    ];
    if t.starts_with("info:") || INFORMATIONAL.iter().any(|s| t.contains(s)) {
        return "informational";
    }

    if t.contains("byte-scan") {
        return "likely_false_positive";
    }

    const PROBABLE: [&str; 13] = [
        "ai:",
        "marker:",
        "meta:",
        "frontmatter",
        "json-ld",
        "attr:",
        "png ",
        "jpeg app",
        "exif",
        "xmp",
        "interesting",
        "pdf-structured",
        "layer-a",
    ];
    if PROBABLE.iter().any(|s| t.contains(s)) {
        return "probable";
    }

    "informational"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_match_python_lengths() {
        assert_eq!(AI_META_HINTS.len(), 17);
        assert_eq!(JPEG_COM_AI_HINTS.len(), 14);
        assert_eq!(ai_and_c2pa_needles().len(), 26);
        assert_eq!(AI_GENERATOR_PRODUCTS.len(), 31);
    }

    #[test]
    fn repr_matches_python() {
        assert_eq!(py_bytes_repr(b"IDAT"), "b'IDAT'");
        assert_eq!(py_bytes_repr(b"a'b"), "b\"a'b\"");
        assert_eq!(py_bytes_repr(b"a'b\"c"), "b'a\\'b\"c'");
        assert_eq!(py_bytes_repr(&[0, 0xff, b'\\', b'\n']), "b'\\x00\\xff\\\\\\n'");
    }

    #[test]
    fn contains_any_is_case_insensitive_and_ordered() {
        let hits = contains_any(b"xx CONTENTCREDENTIALS c2pa", &[b"c2pa", b"C2PA", b"nope"]);
        assert_eq!(hits, vec!["c2pa", "C2PA"]);
    }
}
